#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SbsMobile.Droid.Resource", IsApplication=true)]

namespace SbsMobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000a
			public const int ab_background = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int ab_bottom_shadow_1 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int ab_bottom_shadow_2 = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int action_bar_title_color = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int btn_bg_color = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int btn_bg_shadow_color = 2130968590;
			
			// aapt resource value: 0x7f040008
			public const int main_background = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int sbs_light_blue = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int transparent = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int xam_blue = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int xam_dark_blue = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int xam_gray = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int xam_green = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int xam_light_gray = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int xam_purple = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int btn_corner_radius = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blue_shirt = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_bg_inactive = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_bg_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_bg_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_default_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_default_selected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_default_transparent = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_default_transparent_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cart = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int complete = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int configure = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int discrete_shadow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int drawer_shadow = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dummy_avatar = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int empty_basket = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int gallery_next = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int gallery_prev = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_basket = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_action_logo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_drawer = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_launcher = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_menu_help_holo_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_menu_month = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_menu_share_holo_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int icon2 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ListViewBorder = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int monkey = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int processing = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ProductImage = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int purple_shirt = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int shadow_black = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int shirt_image = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int user_default_avatar = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int wrench = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int btnMenuCalendar = 2131296256;
			
			// aapt resource value: 0x7f090003
			public const int content_frame = 2131296259;
			
			// aapt resource value: 0x7f09000c
			public const int dateDisplay = 2131296268;
			
			// aapt resource value: 0x7f090002
			public const int drawer_layout = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int layoutContainer = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int left_drawer = 2131296260;
			
			// aapt resource value: 0x7f090008
			public const int linearLayout1 = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int linearLayout_dummy1 = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int linearLayout_dummy2 = 2131296266;
			
			// aapt resource value: 0x7f09000d
			public const int menu_tc_calendar = 2131296269;
			
			// aapt resource value: 0x7f090009
			public const int txtCompra = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int txtMenuCalendar = 2131296257;
			
			// aapt resource value: 0x7f090007
			public const int txtMoneda = 2131296263;
			
			// aapt resource value: 0x7f09000b
			public const int txtVenta = 2131296267;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionViewButton = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActionViewTextView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int item_menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SimpleListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TipoCambio = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int tipocambio = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int drawer_close = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int drawer_open = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int icon_calendar = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int menu_calendar = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070006
			public const int SbsMenuButton = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int XamActionBarStyle = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int XamActionBarTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int XamActionBarTitleStyle = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int XamButton = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int XamSubtitleText = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int XamTitleText = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
